<Project Sdk="MSTest.Sdk/4.1.0">
	<Import Project="../../Common.props" />
	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<Platforms>x64</Platforms>
		<PlatformTarget>x64</PlatformTarget>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Materal.Tools.WinUI\Materal.Tools.WinUI.csproj" />
	</ItemGroup>
</Project>
